#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Starting aiychatgpt service...\n"
sudo cp aiychatgpt.service /etc/systemd/system/
sudo chmod 644 /etc/systemd/system/aiychatgpt.service

sudo systemctl start aiychatgpt
sudo systemctl enable aiychatgpt

echo "Success: aiychatgpt script installed!\n"
