#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Starting aiychatgpt service...\n"
cp aiychatgpt.service ~/.config/systemd/user/

systemctl enable --user aiychatgpt
systemctl start --user aiychatgpt

echo "Success: aiychatgpt script installed!\n"
