#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Stopping aiychatgpt service...\n"
systemctl stop --user aiychatgpt
systemctl disable --user aiychatgpt

echo "=> Removing aiychatgpt service...\n"
rm -rf ~/.config/systemd/user/aiychatgpt.service

echo "Success: aiychatgpt service uninstalled!\n"
