#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Stopping aiychatgpt service...\n"
sudo systemctl stop aiychatgpt
sudo systemctl disable aiychatgpt

echo "=> Removing aiychatgpt service...\n"
sudo rm -rf /usr/local/bin/aiychatgpt.py
sudo rm -rf /etc/systemd/system/aiychatgpt.service

echo "Success: aiychatgpt service uninstalled!\n"
